apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: webapp
  name: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      run: webapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: webapp
    spec:
      containers:
      - image: docker.io/cics89/hirshcorp:latest
        name: webapp
        ports:
        - containerPort: 80
        resources: {}
status: {}
